apiVersion: v1
kind: Pod
metadata:
  name: kopspod
  labels: 
    app: myapp
spec:
  containers:
  - name: apache
    image: anilrdy208/appchenewimage:v1
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: kopspod
spec:
  type: NodePort
  selector: 
    app: myapp
  ports:
  - port: 80
    nodePort: 30123
